name: Bug Report
description: File a bug report to help us improve Py-HaloPSA.
title: "[Bug]: "
labels: ["bug"]
projects: ["neschram/Py-HaloPSA"]
assignees:
  - neschram
body:
  - type: markdown
    attributes:
      value: |        
        Thanks!
        We know that submitting a bug report can be time-consuming and may even result in frustration.
        
        Every issue reported allows us to evaluate our project to ensure that we provide the best intentional experience.
        ;p
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code
          - no need for backticks.
      render: shell
  - type: textarea
    id: replication
    attributes:
      label: Steps to reproduce the issue
      description: With as much detail as possible, please submit steps to reproduce the issue described above.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/neschram/Py-HaloPSA/blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow Py-HaloPSA's Code of Conduct.
          required: true
